language: ruby
rvm:
  - 2.2.5
env:
  - DB=pgsql
bundler_args: --without production
before-script:
  - psql -c 'create database courseselect_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
services:
  - postgresql
