language: ruby
rvm:
  - 2.2.5
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake
  - bundle exec rake db:migrate
  - bundle exec rake db:create
services:
  - postgresql
