# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66ce14b857a48c6b7e4960bf0d5b052a69cd25239da97a94b4a08765728e9e124edd7805d66d82c1c2c31924f689dbee1ba9140490f676bd3059079ab1b705e2

test:
  secret_key_base: b70a6b24f68d9b39684c7119efa15f6a1ab48876353e6eee5cdaeeb96ea2abe1bf3051892355941da6ec5eb1d09845f4d26f28e71202b9cd453af412aca95130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
